# Spring profile configuration
spring:
  profiles:
    active: @profileActive@   

# custom properties
jquery:
  demo:
    key: test
    value: test

# kaptcha configuration
kaptcha:  
  session:  
    key: kaptcha.code  
  #border: no  
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy  
  obscurificator:  
    impl: com.google.code.kaptcha.impl.WaterRipple  
  #不要噪点  
  noise:  
    impl: com.google.code.kaptcha.impl.NoNoise  
  image:  
    width: 90  
    height: 33  
  textproducer:  
    font:  
      size: 25  
      color: black  
    char:  
      length: 4  
      space: 5  
  #和登录框背景颜色一致  
  background:  
    clear:  
      from: 247,247,247  
      to: 247,247,247  
          
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@      